---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'assan'

Image:
  extensions:
    - ProductImageExtension
    - LogoImageExtension

SiteConfig:
  extensions:
    - SiteConfigExtension

BootstrapForm:
  bootstrap_included: true
  jquery_included: true
  bootstrap_form_included: false
  bootstrap_select_included: false

Member:
  extensions:
    - MemberExtension

Injector:
  MemberLoginForm:
    class: CustomLoginForm
    priority: 2